version: '3.7'
services:
    postgres:
        image: postgres:14.0
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=mysecretpassword
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        volumes: 
          - ./sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    trips-backend:
        image: qbixer/trips-backend
        depends_on:
          - postgres
        ports:
          - 8081:8081
        environment:
          - SERVER_PORT=8081
          - DBURL=jdbc:postgresql://postgres:5432/trips
          - DBUSER=postgres
          - DBPASS=mysecretpassword
    yourshelfy-backend:
        image: qbixer/yourshelfy-backend
        depends_on:
          - postgres
        ports:
          - 8082:8082
        environment:
          - SERVER_PORT=8082
          - DBURL=jdbc:postgresql://postgres:5432/yourshelfy
          - DBUSER=postgres
          - DBPASS=mysecretpassword
